### 將上傳的資料解壓縮

In [1]:
!wget https://github.com/toonnyy8/mhmc/raw/master/MultimediaProcessing/Data.mat

--2020-08-31 16:06:04--  https://github.com/toonnyy8/mhmc/raw/master/MultimediaProcessing/Data.mat
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/toonnyy8/mhmc/master/MultimediaProcessing/Data.mat [following]
--2020-08-31 16:06:04--  https://raw.githubusercontent.com/toonnyy8/mhmc/master/MultimediaProcessing/Data.mat
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 152437 (149K) [application/octet-stream]
Saving to: ‘Data.mat’

Data.mat            100%[===================>] 148.86K  --.-KB/s    in 0.03s   

2020-08-31 16:06:05 (5.74 MB/s) - ‘Data.mat’ saved [152437/152437]



In [13]:
import scipy.io as sio
data = sio.loadmat('Data.mat')

In [23]:
data["c1"][0][0][0]

array([0.81303898, 0.74135147, 0.55016439, 0.45761272, 0.47286632])

In [22]:
data["c2"][0][0][0]

array([0.99975603, 0.79355586, 0.80790849, 0.94250887, 0.67536667])

In [21]:

data["lable"][0][0][0]

array([1, 0, 0, 0, 0], dtype=uint8)

In [25]:
import tensorflow as tf
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(16,tf.keras.activations.swish),
  tf.keras.layers.Dense(16,tf.keras.activations.swish),
  tf.keras.layers.Dropout(0.3),
  tf.keras.layers.Dense(16,tf.keras.activations.swish),
  tf.keras.layers.Dense(16,tf.keras.activations.swish),
  tf.keras.layers.Dropout(0.3),
  tf.keras.layers.Dense(16,tf.keras.activations.swish),
  tf.keras.layers.Dense(16,tf.keras.activations.softmax),
])